[package]
name = "logistic"
version = "0.1.0"
edition = "2021"
description = "A program to demonstrate the logistic map equation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
